import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineAntDesign,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isHovering, setIsHovered] = useState(false);


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyAli</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/AliHomayed/CV.git"
                >
                  Hire me
                </a>
              </li>
              <li>
                <a
                  className="bg-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="mailto: ali.m.homayed@gmail.com"
                >
                  Contact me
                </a>
              </li>

            </ul>
          </nav>
          <div className="mx-auto rounded-full w-40 h-40  relative overflow-hidden mt-20 ">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Ali Homayed
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-600 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A web developer specialized in Frontend with substantial knowledge in Backend.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400 ">
              <a href="https://github.com/AliHomayed">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/ali-homayed-72025a262/">
                <AiFillLinkedin />
              </a>
              <a href="https://twitter.com/Ali_Homayedd">
                <AiFillTwitterCircle />
              </a>

            </div>

          </div>
        </section>
        <section>
          <div>
            <h3 className="text-4xl py-1 dark:text-white ">The Journey</h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Mechatronics engineer, I admired coding and started learning new languages till I felt the true passion while creating my first
              <span className="text-teal-500"> web application </span>
              . Then, I started my journey of <span className="text-teal-500">self-learning</span>,
              and proudly, I was able to achieve my goal of becoming a web developer.
            </p>

          </div>
          <div className="lg:flex gap-10">
            <div className="text-center  text-gray-800 shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Design
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>

            </div>
            <div className="text-center   text-gray-800 shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Coding
              </h3>
              <p className="py-2">
                Using the latest updates in Visual Studio, javascript, react.js, and next.js.
              </p>

            </div>
            <div className="text-center  text-gray-800 shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Flexibility</h3>
              <p className="py-2">
                Having the skills of being a self-learner as well as using what I have learnt effiecently.
              </p>

            </div>
          </div>
        </section>
      </main>
      <footer className=" text-sm text-center text-gray-400  bg-white px-10  dark:bg-gray-900 md:px-20 lg:px-40 " >
      <a href="https://www.flaticon.com/free-icons/graphic-design" title="graphic design icons">Graphic design icons created by Freepik - Flaticon</a>
      <a href="https://www.flaticon.com/free-icons/learning" title="learning icons">Learning icons created by Paul J. - Flaticon</a>
      <a href="https://www.flaticon.com/free-icons/flexibility" title="flexibility icons">Flexibility icons created by Dewi Sari - Flaticon</a>
    </footer>
    </div>
    
  );
}
